import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home() {
  return (
    <>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.heading}>Welcome to the Project Website</h1>
        <h4 className={styles.para}>To see all the posts, Click the button </h4>
        <Link href="/posts">
          <button className={styles.btn}>See Posts</button>
        </Link>
      </main>
    </>
  );
}
